### ISSUE TITLE
I can't run -close command, error in the description

### ISSUE THREAD

**Issue by ImaZen88** [asapcatftw/DPY-Ticket-Bot#7]
pi@raspberrypi:~ $ /bin/python3 "/home/pi/Desktop/programy/ZenCraft tickets/bot.py"
Lesh go!
Ignoring exception in command close:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/Desktop/programy/ZenCraft tickets/bot.py", line 123, in close
    await CloseTicket(bot, ctx, reason)
  File "/home/pi/Desktop/programy/ZenCraft tickets/utils/util.py", line 253, in CloseTicket
    with open(f"tickets/{ticketId}.txt", "w", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tickets/1.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'tickets/1.txt'

**Comment by ImaZen88** [comment]
Can u help me please?
